<div class="zjlmlb"> <a href="[field:arcurl/]"><img src="[field:litpic/]" /></a>
          <p class="pnm1"> <font class="name">[field:title/]</font> | <font>[field:shorttitle/]</font> </p>
          <p>[field:infos/]</p>
          <div> <a href="tel:028-64235120" rel="nofollow"><i class="fa fa-phone"></i><span>电话咨询</span></a> <a href="" rel="nofollow"><i class="fa fa-commenting-o" aria-hidden="true"></i><span>在线咨询</span></a> <a href="[field:arcurl/]" title="[field:title/]"><i class="fa fa-plus-square"></i><span>医生简介</span></a> </div>
        </div>