<?php
$z[0]=Array("global","",63,95);
$z[0][4]['name']="cfg_templets_skin";
$z[1]=Array("global","",177,209);
$z[1][4]['name']="cfg_templets_skin";
$z[2]=Array("global","",310,342);
$z[2][4]['name']="cfg_templets_skin";
$z[3]=Array("channelartlist","\r\n    <li> <a href=\"{dede:field.typeurl/}\">\r\n      <p>{dede:field.typename/}</p>\r\n      </a> </li>\r\n    ",423,585);
$z[3][4]['typeid']="1,2,3";
$z[4]=Array("channelartlist","\r\n    <li> <a href=\"{dede:field.typeurl/}\">\r\n      <p>{dede:field.typename/}</p>\r\n      </a> </li>\r\n    ",675,837);
$z[4][4]['typeid']="4,5,6";

?>