<?php
$z[0]=Array("field","",222,244);
$z[0][4]['name']="typename";
$z[1]=Array("field","",285,307);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",347,372);
$z[2][4]['name']="description";
$z[3]=Array("global","",399,431);
$z[3][4]['name']="cfg_templets_skin";
$z[4]=Array("global","",496,528);
$z[4][4]['name']="cfg_templets_skin";
$z[5]=Array("include","",572,609);
$z[5][4]['filename']="header.htm";
$z[6]=Array("field","",696,718);
$z[6][4]['name']="position";
$z[7]=Array("channelartlist","\r\n      <li><a>{dede:field.typename/}</a></li>\r\n      ",816,945);
$z[7][4]['typeid']="7,14,21,28,35,36,37,38";
$z[8]=Array("list","\r\n        <div class=\"zjlmlb\"> <a href=\"[field:arcurl/]\"><img src=\"[field:litpic/]\" /></a>\r\n          <p class=\"pnm1\"> <font class=\"name\">[field:title/]</font> | <font>[field:shorttitle/]</font> </p>\r\n          <p>[field:infos/]</p>\r\n          <div> <a href=\"tel:028-64235120\" rel=\"nofollow\"><i class=\"fa fa-phone\"></i><span>电话咨询</span></a> <a href=\"\" rel=\"nofollow\"><i class=\"fa fa-commenting-o\" aria-hidden=\"true\"></i><span>在线咨询</span></a> <a href=\"[field:arcurl/]\" title=\"[field:title/]\"><i class=\"fa fa-plus-square\"></i><span>医生简介</span></a> </div>\r\n        </div>\r\n        ",1073,1712);
$z[8][4]['pagesize']="10";
$z[9]=Array("global","",2157,2189);
$z[9][4]['name']="cfg_templets_skin";

?>